SELECT
    A.ITNO AS 'ITNO',
    A.SERN AS 'SERN',
    B.ITDS AS 'ITDS'
FROM
    MILOIN A
LEFT OUTER JOIN
    MITMAS B ON A.ITNO = B.ITNO AND B.CONO = A.CONO
WHERE
    B.ITTY = 100
    AND A.STAT = '20'
    AND A.CONO = '860'
