select 
A.BIRT as 'ID',
A.ITNO as 'BAUREIHE',
A.ACRF as 'ACRF',
D.ACMC as 'ACMC',
A.SERN as 'SERIENNUMMER',
A.ALII as 'WAGEN-TYP',
A.CUNO as 'KUNDEN-NUMMER',
B.CUNM as 'KUNDEN-NAME',
C.WHLO as 'LAGERORT',
C.WHSL as 'LAGERPLATZ'
from MILOIN A
LEFT OUTER JOIN OCUSMA B on A.CUNO = B.CUNO and B.CONO = A.CONO
LEFT OUTER JOIN (
  SELECT CONO, ITNO, BANO, MAX("TIMESTAMP") AS MAX_TIMESTAMP
  FROM MITLOC
  GROUP BY CONO, ITNO, BANO
) CM on A.ITNO = CM.ITNO and A.SERN = CM.BANO and CM.CONO = A.CONO
LEFT OUTER JOIN MITLOC C on A.ITNO = C.ITNO and A.SERN = C.BANO and C.CONO = A.CONO and C."TIMESTAMP" = CM.MAX_TIMESTAMP
LEFT OUTER JOIN MITMAS D on A.ITNO = D.ITNO and D.CONO = A.CONO
where A.EQTP = '100' and A.STAT = '20' and A.CONO = '881'
